
package tablahilo;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author Fabian
 */
public class interfaz extends javax.swing.JFrame implements Runnable {
public static String f;
public static int valor1, valor2, valor3, result;

Thread hilo1, hilo2, hilo3;

    public interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cargar1 = new javax.swing.JButton();
        cargar2 = new javax.swing.JButton();
        cargar3 = new javax.swing.JButton();
        n1 = new javax.swing.JTextField();
        n2 = new javax.swing.JTextField();
        n3 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        m1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        m2 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        m3 = new javax.swing.JTextArea();
        pausar1 = new javax.swing.JButton();
        pausar2 = new javax.swing.JButton();
        pausar3 = new javax.swing.JButton();
        borrar1 = new javax.swing.JButton();
        borrar2 = new javax.swing.JButton();
        borrar3 = new javax.swing.JButton();
        continuar1 = new javax.swing.JButton();
        continuar2 = new javax.swing.JButton();
        continuar3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Numero:");

        jLabel2.setText("Numero:");

        jLabel3.setText("Numero:");

        cargar1.setText("Cargar");
        cargar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cargar1MouseClicked(evt);
            }
        });
        cargar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargar1ActionPerformed(evt);
            }
        });

        cargar2.setText("Cargar");
        cargar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargar2ActionPerformed(evt);
            }
        });

        cargar3.setText("Cargar");
        cargar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargar3ActionPerformed(evt);
            }
        });

        n2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n2ActionPerformed(evt);
            }
        });

        m1.setColumns(20);
        m1.setRows(5);
        jScrollPane1.setViewportView(m1);

        m2.setColumns(20);
        m2.setRows(5);
        jScrollPane2.setViewportView(m2);

        m3.setColumns(20);
        m3.setRows(5);
        jScrollPane3.setViewportView(m3);

        pausar1.setText("pause");
        pausar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pausar1ActionPerformed(evt);
            }
        });

        pausar2.setText("pause");
        pausar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pausar2ActionPerformed(evt);
            }
        });

        pausar3.setText("pause");
        pausar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pausar3ActionPerformed(evt);
            }
        });

        borrar1.setText("borrar");
        borrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrar1ActionPerformed(evt);
            }
        });

        borrar2.setText("borrar");
        borrar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrar2ActionPerformed(evt);
            }
        });

        borrar3.setText("borrar");
        borrar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrar3ActionPerformed(evt);
            }
        });

        continuar1.setText("continuar");
        continuar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continuar1ActionPerformed(evt);
            }
        });

        continuar2.setText("continuar");
        continuar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continuar2ActionPerformed(evt);
            }
        });

        continuar3.setText("continuar");
        continuar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continuar3ActionPerformed(evt);
            }
        });

        jButton1.setText("Reset");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Salir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cargar1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(n1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pausar1)
                            .addComponent(borrar1)
                            .addComponent(continuar1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(24, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(n2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cargar2)
                            .addComponent(jLabel2)))
                    .addComponent(pausar2)
                    .addComponent(borrar2)
                    .addComponent(continuar2))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cargar3)
                                    .addComponent(n3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(46, 46, 46)))
                        .addGap(12, 12, 12)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(continuar3)
                        .addGap(77, 77, 77)
                        .addComponent(jButton3))
                    .addComponent(borrar3)
                    .addComponent(pausar3))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(n1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(n2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(n3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1)))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cargar1)
                    .addComponent(cargar2)
                    .addComponent(cargar3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(pausar2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(borrar2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(continuar2))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(pausar3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(borrar3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(continuar3)
                            .addComponent(jButton3)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(pausar1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(borrar1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(continuar1)))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void n2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_n2ActionPerformed

    private void cargar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cargar1MouseClicked
      
    }//GEN-LAST:event_cargar1MouseClicked

    private void cargar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargar1ActionPerformed
      IniciarHilo1();
      pausar1.setEnabled(true);
      borrar1.setEnabled(true);
      continuar1.setEnabled(true);
      cargar1.setVisible(false);
        
    }//GEN-LAST:event_cargar1ActionPerformed

    private void cargar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargar2ActionPerformed
        IniciarHilo2();
        pausar2.setEnabled(true);
        borrar2.setEnabled(true);
        continuar2.setEnabled(true);
        cargar2.setVisible(false);
    }//GEN-LAST:event_cargar2ActionPerformed

    private void cargar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargar3ActionPerformed
        IniciarHilo3(); 
        pausar3.setEnabled(true);
        borrar3.setEnabled(true);
        continuar3.setEnabled(true);
        cargar3.setVisible(false);
    }//GEN-LAST:event_cargar3ActionPerformed

    private void pausar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pausar1ActionPerformed
        hilo1.suspend();
    }//GEN-LAST:event_pausar1ActionPerformed

    private void borrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrar1ActionPerformed
         hilo1.stop();
         m1.setText("");
         cargar1.setVisible(true);
    }//GEN-LAST:event_borrar1ActionPerformed

    private void continuar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continuar1ActionPerformed
        hilo1.resume(); 
    }//GEN-LAST:event_continuar1ActionPerformed

    private void pausar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pausar2ActionPerformed
       hilo2.suspend(); 
    }//GEN-LAST:event_pausar2ActionPerformed

    private void borrar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrar2ActionPerformed
         hilo2.stop();
         m2.setText("");
         cargar2.setVisible(true);
    }//GEN-LAST:event_borrar2ActionPerformed

    private void continuar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continuar2ActionPerformed
         hilo2.resume(); 
    }//GEN-LAST:event_continuar2ActionPerformed

    private void pausar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pausar3ActionPerformed
       hilo3.suspend();
    }//GEN-LAST:event_pausar3ActionPerformed

    private void borrar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrar3ActionPerformed
        hilo3.stop();
        m3.setText("");
        cargar3.setVisible(true);
    }//GEN-LAST:event_borrar3ActionPerformed

    private void continuar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continuar3ActionPerformed
        hilo3.resume(); 
    }//GEN-LAST:event_continuar3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        n1.setText("");
        n2.setText("");
        n3.setText("");
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed
 public void proceso1(){
     valor1 = Integer.parseInt(n1.getText());
       for (int i = 0; i >= 0; i++) {
           result = valor1 * i;
           f = String.valueOf(result);
           f = Integer.toString(result);
           m1.append(valor1+" x "+i+ " = " +f+ "\n");
            try {
        Thread.sleep(100);
    } catch (InterruptedException ex) {
        Logger.getLogger(interfaz.class.getName()).log(Level.SEVERE, null, ex);
    }  
       }
       
     
   }
   public void proceso2(){
       valor2 = Integer.parseInt(n2.getText());
       for (int i = 0; i >= 0; i++) {
           result = valor2 * i;
           f = String.valueOf(result);
           f = Integer.toString(result);
           m2.append(valor2+" x "+i+ " = " +f+ "\n");
            try {
        Thread.sleep(100);
    } catch (InterruptedException ex) {
        Logger.getLogger(interfaz.class.getName()).log(Level.SEVERE, null, ex);
    }  
       }
       
   }
   public void proceso3(){
       valor3 = Integer.parseInt(n3.getText());
       for (int i = 0; i >= 0; i++) {
           result = valor3 * i;
           f = String.valueOf(result);
           f = Integer.toString(result);
           m3.append(valor3+" x "+i+ " = " +f+ "\n");
            try {
        Thread.sleep(100);
    } catch (InterruptedException ex) {
        Logger.getLogger(interfaz.class.getName()).log(Level.SEVERE, null, ex);
    }  
       }
       
   }
    
    public void IniciarHilo1(){
    hilo1=new Thread((Runnable) this);
    hilo1.start();
    
    
}
public void IniciarHilo2(){
    hilo2=new Thread((Runnable) this);
    hilo2.start();
}
public void IniciarHilo3(){
    hilo3=new Thread((Runnable) this);
    hilo3.start();
}
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfaz().setVisible(true);
               
            }
        });
    }
    public void run(){
       Thread ct = Thread.currentThread();
      while(ct == hilo1){
          proceso1();
      }
      while(ct == hilo2){
          proceso2();
      }
      while(ct == hilo3){
          proceso3();
      }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton borrar1;
    private javax.swing.JButton borrar2;
    private javax.swing.JButton borrar3;
    private javax.swing.JButton cargar1;
    private javax.swing.JButton cargar2;
    private javax.swing.JButton cargar3;
    private javax.swing.JButton continuar1;
    private javax.swing.JButton continuar2;
    private javax.swing.JButton continuar3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea m1;
    private javax.swing.JTextArea m2;
    private javax.swing.JTextArea m3;
    public static javax.swing.JTextField n1;
    private javax.swing.JTextField n2;
    private javax.swing.JTextField n3;
    private javax.swing.JButton pausar1;
    private javax.swing.JButton pausar2;
    private javax.swing.JButton pausar3;
    // End of variables declaration//GEN-END:variables

}
    
